### ISSUE TITLE
Receiving [ Session [(null externalkey)] not available and is not among the last 1000 terminated ] when attempting to connect via Selenium Grid

### ISSUE THREAD

**Issue by mikesalvia** [appium/ruby_lib#541] opened 2017-04-14 15:59 UTC
Framework: Capybara

Using:
- Appium: 1.6.4
- Selenium: 3.3.1
- appium_lib: 9.x
- appium_capybara: 1.3.0

**NOTE: this setup is working 100% using Java clients from another framework.**

The issue is with the 9.x versions of `appium_lib` and the latest versions of both Appium (1.6.4) and Selenium (3.3.1).

I am using Selenium in hub mode and connecting Appium to it. This works as expected.

When using the latest version of `appium_lib` whenever I attempt to make a connection via Selenium to Appium, everything connects starts going an I even get "Let's browse..." page, then immediately the session is ended and I receive...

`Session [(null externalkey)] not available and is not among the last 1000 terminated`

Logs can be made available as needed.

I have found a workaround which is not ideal but does work. Basically, after installing the `appium_lib` gem unsing `bundle install` I need to downgrade to 8.0.2, also I need to remove `selenium-webdriver` 3.3.0 that is included in `capybara` gem and install version greater than `2.49.x` but less than `3.x.x`. This causes a bunch of other issues with gems that require `3.x.x.` or above.

This issue has also been reported: https://github.com/appium/appium/issues/7677

It appears that for some reason either `appium_lib` isn't communicating session information correctly or is timing out.

Please let me know what other information I can provide!

**Comment by mykola-mokhnach** [comment] 2017-04-14 16:45
Duplicate of https://github.com/appium/appium/issues/7677

**Comment by KazuCocoa** [comment] 2017-04-14 23:58
Thanks!
I understood.

The reason why `appium_lib` require selenium-webdriver 3.0+ from 9.1.0, `find_element/s` is broken when I upgraded selenium-webdriver 2.x to 3.x for appium_lib and I've fixed it.
https://github.com/appium/ruby_lib/blob/master/CHANGELOG.md#v910
https://github.com/appium/ruby_lib/blob/master/CHANGELOG.md#v913

@mikesalvia 
I just prepared a branch which requires 2+ based on `appium_lib` 9.3.8.
Could you try this? Don't forget set `selenium-webdriver, '~> 2.49.0'` in your gemfile.
https://github.com/KazuCocoa/ruby_lib/tree/require_over_selenium_webdriver2

**Comment by KazuCocoa** [comment] 2017-04-15 00:05
memos for me

Capybara supports `selenium-webdriver` 3.x [gemspec](https://github.com/teamcapybara/capybara/blob/master/capybara.gemspec#L31), but appium_capybara.
`appium_capybara` requires `'capybara', '~> 2.7'` [gemspec](https://github.com/appium/appium_capybara/blob/master/appium_capybara.gemspec).

**Comment by mikesalvia** [comment] 2017-05-18 16:30
@KazuCocoa I will look into this ASAP thank you! :+1:

**Comment by KazuCocoa** [comment] 2017-05-18 23:03
https://github.com/appium/appium_capybara/issues/29

**Comment by KazuCocoa** [comment] 2017-05-21 05:23
@mikesalvia 
I've been investigating...
I guess if you set `version` in ruby_lib's capability addition to `browserName` may work with latest appium_lib since `appium_lib` start using [Selenium::WebDriver::Remote::Capabilities.new](https://github.com/appium/ruby_lib/blob/master/lib/appium_lib/driver.rb#L265) with selenium-webdriver3.x.

----
----

Your attached logs have non-blank `browserName` and blank `version` but grid uses each value. So, I assume if you set `version`, grid will work...

```
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"rotatable":false,"nativeEvents":false,"newCommandTimeout":"300","platformVersion":"6.0","browserName":"chrome","takesScreenshot":true,"javascriptEnabled":true,"platformName":"android","version":"","deviceName":"0715f7c4c56a0b36","platform":"ANY","cssSelectorsEnabled":true},null,null,null,null]
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   rotatable: false
[Appium]   nativeEvents: false
[Appium]   newCommandTimeout: '300'
[Appium]   platformVersion: '6.0'
[Appium]   browserName: 'chrome'
[Appium]   takesScreenshot: true
[Appium]   javascriptEnabled: true
[Appium]   platformName: 'android'
[Appium]   version: ''
[Appium]   deviceName: '0715f7c4c56a0b36'
[Appium]   platform: 'ANY'
[Appium]   cssSelectorsEnabled: true
[Appium]   udid: '0715f7c4c56a0b36'
```


I'm sorry my late investigation since I haven't been used Grid in my environment... 😢

**Comment by KazuCocoa** [comment] 2017-05-21 05:37
memo:

https://github.com/SeleniumHQ/selenium/tree/master/java/server/src/org/openqa/grid

**Comment by KazuCocoa** [comment] 2017-05-21 12:28
related to this issue...?
https://github.com/SeleniumHQ/selenium/issues/1985

**Comment by KazuCocoa** [comment] 2017-05-21 12:56
the error message comes from  https://github.com/SeleniumHQ/selenium/blob/ceaf3da79542024becdda5953059dfbb96fb3a90/java/server/src/org/openqa/grid/internal/ActiveTestSessions.java#L97

**Comment by mikesalvia** [comment] 2017-05-21 20:33
@KazuCocoa I didn't post any logs, BUT that you for the insight. We got this for iOS, I noticed the snippet you provided was for Android (Chrome).

**Comment by KazuCocoa** [comment] 2017-05-22 01:06
@mikesalvia 
Oops, thanks.
I mistook. The log in https://github.com/appium/ruby_lib/issues/541#issuecomment-302916016 is https://github.com/appium/appium/issues/7677's other user's one. Sorry.

FYI,
I just updated the branch https://github.com/KazuCocoa/ruby_lib/tree/require_over_selenium_webdriver2 I mentioned in https://github.com/appium/ruby_lib/issues/541#issuecomment-294258045

**Comment by KazuCocoa** [comment] 2017-05-22 10:17
memo:

`appium_lib` start using `::Selenium::WebDriver::Remote::Capabilities.new(default_caps_opts_firefox)`, [here](https://github.com/appium/ruby_lib/blob/4d986830facd0e4ef1978e247a3c8ffd0a02427b/lib/appium_lib/driver.rb#L265 ), to generate capability from v9.1.0.
So, if this error will be caused by the capability, this error happen against 9.1+.

https://github.com/appium/ruby_lib/blob/master/release_notes.md#v900-2016-12-09

I'll try to replace the capability and hack selenium-webdriver to check the problem is its capability or not.

**Comment by KazuCocoa** [comment] 2017-06-04 11:45
grid: https://github.com/SeleniumHQ/selenium/tree/master/java/server/src/org/openqa/grid

**Comment by KazuCocoa** [comment] 2017-06-11 01:10
https://github.com/appium/ruby_lib/pull/600 will fix 500 status code error.

**Comment by KazuCocoa** [comment] 2017-06-11 01:11
But I couldn't reproduce `[ Session [(null externalkey)] not available and is not among the last 1000 terminated ]` error in my environment yet.

**Comment by KazuCocoa** [comment] 2017-06-11 11:19
publish 9.4.7, fixed #600
Could you try 9.4.7 if you have a time? @mikesalvia

**Comment by KazuCocoa** [comment] 2017-06-12 22:28
According to https://github.com/appium/appium/issues/8492, 9.4.7 works via Grid.

**Comment by mikesalvia** [comment] 2017-06-16 18:25
I will try this weekend sorry for the delay! :-)

**Comment by mikesalvia** [comment] 2017-06-19 20:30
@KazuCocoa So I tried the update `gem`... Are there any limitations for other dependencies that this will require? As of right now it appears to still not work. :-(

**Comment by KazuCocoa** [comment] 2017-06-20 01:43
hm...
Settings I've checked behaviour for the grid in this repository is https://github.com/appium/ruby_lib/tree/master/grid .

Could you attach configurations for the target?
I guess this issue is associated with `browserName`, grid side, and `deviceName`, Appium side.

**Comment by mikesalvia** [comment] 2017-06-20 14:22
I will add after reviewing the docs at that link.

**Comment by mikesalvia** [comment] 2017-06-20 14:23
Did you check behavior using 2.53.1 or 3 for Selenium Grid?

**Comment by KazuCocoa** [comment] 2017-06-20 14:26
Both is ok but please use  2.53.1 at first.

**Comment by mikesalvia** [comment] 2017-06-20 14:26
OK will attempt setup and see what I can verify.

**Comment by mikesalvia** [comment] 2017-07-12 23:40
Version 9.4.9 seems to resolve this issue!!!

**Comment by KazuCocoa** [comment] 2017-07-13 00:17
Thanks for your checking!! :+1:

**Closed** 2017-07-13 01:14 UTC
Labels: bug, enhancement
