### ISSUE TITLE
promote_appium_methods provokes a wrong cause in Selenium::WebDriver::Errors

### ISSUE THREAD

**Issue by dgmora** [appium/ruby_lib#369] opened 2016-04-21 15:58 UTC
I used `Appium.promote_appium_methods(class)`, and in a instance of this class, I used `wait_true` with `finds_exact` to try to find something.

When the element is not found, the exception I get is something like this:

```
     Selenium::WebDriver::Error::NoSuchElementError:
       An element could not be located on the page using the given search parameters.
     # ./spec/login_spec.rb:12:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   super: no superclass method `find_exact' for #<LoginView:0x007fe453ba4160>
     #   Did you mean?  finds_exact
     #   ./spec/login_spec.rb:12:in `block (2 levels) in <top (required)>'
```

Same happens with `wait_true` and other finder methods.

I found that this is because the methods defined by `Appium.promote_appium_methods` try to call the parent and swallow `NoMethodError`. This exception is set as the cause for the `Selenium::WebDriver::Error::NoSuchElementError`. I'm not very sure where this is set as the cause, or how to avoid it.

**Comment by bootstraponline** [comment] 2016-04-21 16:31
If you could post a reduced test case as a gist that demonstrates the problem, that'd be helpful.

**Comment by dgmora** [comment] 2016-04-21 17:39
By doing the gist I found out it's actually RSpec adding the cause magically.

https://gist.github.com/dgmora/114663e32632e9c2bff4835eba30deec

**Comment by bootstraponline** [comment] 2016-04-21 17:41
Does it work if you promote on Object?

```diff
- Appium.promote_appium_methods(Foo)
+ Appium.promote_appium_methods(Object)
```

**Comment by dgmora** [comment] 2016-04-21 17:44
Same result when running it with rspec.

**Comment by bootstraponline** [comment] 2016-04-21 17:47
Weird. I'm guessing it's a bug in the promotion logic then. In general I recommend avoiding `promote_appium_methods` since it's kind of a hack.

**Comment by dgmora** [comment] 2016-04-21 17:50
Ok, we might stop using it. The reason for that is that the exception raised by  `wait_true`, has a `NoMethodError` as a cause, and rspec adds the cause if it's there. Not sure why it is set as the cause though.

**Comment by bootstraponline** [comment] 2016-04-21 17:56
Based on the error `no superclass method 'wait_true'`, the `promote_appium_methods` failed to correctly define the wait_true method. Debugging monkey patching in ruby is painful.

**Comment by sofaking** [comment] 2016-04-22 16:20
Just FYI, I'm using both promote_appium_methods and promote_singleton_appium_methods for a couple of years now in a handful of different test suites. Both work well (although every time I dream about something more Rubyish, like inheritance). 

The thing is I'm using Cucumber most of the time, with or without RSpec matchers, but still Cucumber. So I guess the issue has something to do with RSpec and the way it treats objects inside its describe DSL.

**Comment by bootstraponline** [comment] 2016-04-22 16:31
I know RSpec has an include option:

```ruby
RSpec.configure do |config|
  config.include Some::Class
end
```

not sure if that works with the appium bindings.

**Comment by dgmora** [comment] 2016-04-22 17:51
...That might work if you want to use appium methods directly in the spec, but if you want to use appium methods in another class (say, `LoginView.new.find_exact('login)`) won't help. 

The problem is why `no superclass method 'wait_true'` is set as the cause for the `Selenium::WebDriver::Error::NoSuchElementError`.
If you rescue the `Selenium::WebDriver::Error::NoSuchElementError`, you see that `e.cause` is  `no superclass method 'wait_true'`

**Comment by bootstraponline** [comment] 2016-04-22 20:32
I understand now. The code works correctly, only the `error.cause` is useless. I'll try and figure out what specific code is responsible for setting the cause.

**Comment by bootstraponline** [comment] 2016-04-22 20:36
This is where the `Caused by` line is added:
- [exception_presenter](https://github.com/rspec/rspec-core/blob/cf8dfdc76586a9bb09da0bd03f0da3f2cf8fc580/lib/rspec/core/formatters/exception_presenter.rb#L42)

pretty sure this is a bug / limitation in rspec-core unrelated to `appium/ruby_lib`.

**Comment by bootstraponline** [comment] 2016-04-22 20:42
I reduced the issue further:

```ruby
require 'appium_lib'
Appium::Driver.new(caps: {})
Appium.promote_appium_methods(Object)

begin
  wait_true(timeout: 1){ 2 == 1 }
rescue => e
  puts "cause: #{e.cause}"
end
```

`appium/ruby_lib` isn't setting the cause correctly so it's not an rspec issue after all. I'm not actually sure how we'd fix this.

**Comment by bootstraponline** [comment] 2016-04-22 21:06
```diff
diff --git a/lib/appium_lib/driver.rb b/lib/appium_lib/driver.rb
index 4c0adae..782973b 100644
--- a/lib/appium_lib/driver.rb
+++ b/lib/appium_lib/driver.rb
@@ -172,11 +172,7 @@ module Appium
       # noinspection RubyResolve
       $driver.public_methods(false).each do |m|
         const.send(:define_singleton_method, m) do |*args, &block|
-          begin
-            super(*args, &block) # promote.rb
-          rescue NoMethodError, ArgumentError
-            $driver.send m, *args, &block if $driver.respond_to?(m)
-          end
+          $driver.send m, *args, &block if $driver.respond_to?(m)
           # override unless there's an existing method with matching arity
         end unless const.respond_to?(m) && const.method(m).arity == $driver.method(m).arity
       end
@@ -214,17 +210,7 @@ module Appium
       $driver.public_methods(false).each do |m|
         klass.class_eval do
           define_method m do |*args, &block|
-            begin
-              # Prefer existing method.
-              # super will invoke method missing on driver
-              super(*args, &block)
-
-              # minitest also defines a name method,
-              # so rescue argument error
-              # and call the name method on $driver
-            rescue NoMethodError, ArgumentError
-              $driver.send m, *args, &block if $driver.respond_to?(m)
-            end
+            $driver.send m, *args, &block if $driver.respond_to?(m)
           end
         end
       end
```

If you don't care about method clobbering ^ will work.

**Comment by bootstraponline** [comment] 2016-04-22 21:45
https://github.com/appium/ruby_lib/pull/370 should be a real fix. let me know if it works.

**Comment by KazuCocoa** [comment] 2017-02-26 15:25
> #370 should be a real fix. let me know if it works.

so, close this.

**Closed by KazuCocoa** 2017-02-26 15:25 UTC

**Comment by laiyuncong8404** [comment] 2017-09-27 09:02
* appium version
1.6.5
* rspec version
rspec (3.5.0)
rspec-core (3.5.4)
rspec-expectations (3.5.0)
rspec-mocks (3.5.0)
rspec-support (3.5.0)

I still have the same issue after update appium_lib from '9.6.0' to '9.6.1'
rspec log as blow:

`Selenium::WebDriver::Error::NoSuchElementError:
       An element could not be located on the page using the given search parameters.
     # ./iOS_pub_test_spec.rb:102:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   super: no superclass method `last_ele' for #<RSpec::ExampleGroups::MQTTIOSPub:0x007ff52ab66c60>
     #   Did you mean?  last_textfield
     #   ./iOS_pub_test_spec.rb:102:in `block (2 levels) in <top (required)>'`

**Comment by KazuCocoa** [comment] 2017-09-27 15:06
thanks!

@laiyuncong8404 
Do you mean it works well with `9.6.0`?

Could you try `Appium::Driver.new(opts, true).start_driver` to use global scope driver?
^'s diff is around [here](https://github.com/appium/ruby_lib/compare/v9.6.0...v9.6.1#diff-3108f19537d63910373ca896fc8ac6a7L390).

**Comment by laiyuncong8404** [comment] 2017-09-28 05:43
@KazuCocoa 
Thanks for your quick reply.
I mean both `9.6.0` and `9.6.1 `are NOT work.
after initialize driver with `Appium::Driver.new(opts, true).start_driver`,
 it's work now on `9.6.1`.

But I get another problem, I want to run these spec files together, so I write a `spec_helper.rb` file like this, 

```ruby
require 'rspec'
require 'appium_lib'

def setup_driver
	return if $driver
	appium_txt  = File.expand_path(File.join(File.dirname(__FILE__), 'appium.txt'))
	@caps = Appium.load_appium_txt file: appium_txt, verbose: true
	Appium::Driver.new (@caps)
end

def promote_methods
	Appium.promote_appium_methods RSpec::Core::ExampleGroup
end

RSpec.configure do |config|
	config.run_all_when_everything_filtered = true
	config.alias_it_should_behave_like_to :include_shared
	config.before (:suite) do
		setup_driver
		$driver.start_driver
		promote_methods
	end

	config.before (:all) do
		set_wait (120)
	end

	config.after (:suite) do
		$driver.driver_quit
	end
end
```
then I got the same problem because i can not generate global driver by passing `true`to it.
rspec log as blow:
```shell
  Failure/Error: text_exact('Add Connection').click

  Selenium::WebDriver::Error::UnknownError:
    Method is not implemented
  # ./iOS_pub_appium+ruby_spec.rb:21:in `block (2 levels) in <top (required)>'
  # ------------------
  # --- Caused by: ---
  # NoMethodError:
  #   super: no superclass method `text_exact' for #<RSpec::ExampleGroups::MQTTIOSPub:0x007fc34c951b10>
  #   Did you mean?  texts_exact
  #   ./iOS_pub_appium+ruby_spec.rb:21:in `block (2 levels) in <top (required)>'
./iOS_pub_appium+ruby_spec.rb:21:in `block (2 levels) in <top (required)>'
------------------
--- Caused by: ---
NoMethodError:
  super: no superclass method `text_exact' for #<RSpec::ExampleGroups::MQTTIOSPub:0x007fc34c951b10>
  Did you mean?  texts_exact
  ./iOS_pub_appium+ruby_spec.rb:21:in `block (2 levels) in <top (required)>'
```
Appium log shows like
```shell
2017-09-28 13:40:12:368 - [Appium] New XCUITestDriver session created successfully, session 06ec3d3a-616f-4f91-a4d6-8a9393ae98fa added to master session list
2017-09-28 13:40:12:377 - [HTTP] <-- POST /wd/hub/session 200 22367 ms - 574
2017-09-28 13:40:12:387 - [HTTP] --> GET /wd/hub/status {}
2017-09-28 13:40:12:457 - [HTTP] <-- GET /wd/hub/status 200 67 ms - 83
2017-09-28 13:40:12:463 - [HTTP] --> POST /wd/hub/session/06ec3d3a-616f-4f91-a4d6-8a9393ae98fa/timeouts/implicit_wait {"ms":0}
2017-09-28 13:40:12:537 - [HTTP] <-- POST /wd/hub/session/06ec3d3a-616f-4f91-a4d6-8a9393ae98fa/timeouts/implicit_wait 200 74 ms - 76
2017-09-28 13:40:12:542 - [HTTP] --> POST /wd/hub/session/06ec3d3a-616f-4f91-a4d6-8a9393ae98fa/timeouts/implicit_wait {"ms":120000}
2017-09-28 13:40:12:563 - [HTTP] <-- POST /wd/hub/session/06ec3d3a-616f-4f91-a4d6-8a9393ae98fa/timeouts/implicit_wait 200 17 ms - 76
2017-09-28 13:40:12:566 - [HTTP] --> POST /wd/hub/session/06ec3d3a-616f-4f91-a4d6-8a9393ae98fa/execute {"script":"        (function() {\n          var opts = {\"typeArray\":[\"UIAStaticText\"],\"onlyVisible\":true,\"name\":{\"target\":\"Add Connection\",\"substring\":false,\"insensitive\":false},\"label\":{\"target\":\"Add Connection\",\"substring\":false,\"insensitive\":false},\"value\":{\"target\":\"Add Connection\",\"substring\":false,\"insensitive\":false},\"onlyFirst\":true};\n          var result = false;\n\n          try {\n            result = $._elementOrElementsByType($.mainWindow(), opts);\n          } catch (e) {\n          }\n\n          return result;\n        })();\n","args":[]}
2017-09-28 13:40:12:603 - [HTTP] <-- POST /wd/hub/session/06ec3d3a-616f-4f91-a4d6-8a9393ae98fa/execute 501 37 ms - 112
2017-09-28 13:40:12:827 - [HTTP] --> DELETE /wd/hub/session/06ec3d3a-616f-4f91-a4d6-8a9393ae98fa {}
2017-09-28 13:40:13:209 - [XCUITest] Shutting down sub-processes
2017-09-28 13:40:13:210 - [XCUITest] Shutting down xcodebuild process (pid 6957)
2017-09-28 13:40:13:233 - [XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
2017-09-28 13:40:13:247 - [XCUITest] Setting '755' permissions to '/Users/xiaoxue/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments' folder
2017-09-28 13:40:13:253 - [Appium] Removing session 06ec3d3a-616f-4f91-a4d6-8a9393ae98fa from our master session list
2017-09-28 13:40:13:265 - [HTTP] <-- DELETE /wd/hub/session/06ec3d3a-616f-4f91-a4d6-8a9393ae98fa 200
```

**Comment by KazuCocoa** [comment] 2017-09-28 05:53
@laiyuncong8404 
Thanks!

I'll take a look after my work.
Could you create a new issue against the latest comment, https://github.com/appium/ruby_lib/issues/369#issuecomment-332733618?

**Comment by laiyuncong8404** [comment] 2017-09-28 07:55
Pls refer to #672 , thank you!
