### ISSUE TITLE
Doc issue - press_keycode

### ISSUE THREAD

**Issue by xsmaster** [appium/ruby_lib#318] opened 2015-04-06 21:40 UTC
the list of methods in the doc's on => https://github.com/appium/ruby_lib/blob/master/docs/docs.md

is missing "press_keycode" its a very useful feature for Android. 

http://developer.android.com/reference/android/view/KeyEvent.html <-- The list of all the keyboard int values.

**Comment by bootstraponline** [comment] 2015-04-06 21:53
Check the [android_docs](https://github.com/appium/ruby_lib/blob/master/docs/android_docs.md), those are auto generated from the source & always up to date.

**Comment by bootstraponline** [comment] 2015-04-06 21:54
dupe of #237

**Closed by bootstraponline** 2015-04-06 21:53 UTC

**Comment by xsmaster** [comment] 2015-04-07 00:32
Woops. Thanks mate
