### ISSUE TITLE
Element not displayed question and maybe bug?

### ISSUE THREAD

**Issue by uscengineer** [appium/ruby_lib#347] opened 2015-08-15 20:36 UTC
In a test I verify that a textfield is displayed. It keeps returning false. The inspector shows visibility also as false. Looking at the screen xml it look there are parent and child elements with the same value but the parent has visible=false while the child has it set to true.

 `               <UIATableCell name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/1/0/3" x="0" y="283.109375" width="375" height="62.109375">
                    <UIAButton name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/1/0/3/0" x="5.859375" y="288.96875" width="281.25" height="38.671875">
                    </UIAButton>
                    <UIATextField name="" label="" value="Birthday" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/1/0/3/1" x="51.5625" y="300.6875" width="281.25" height="28.125">
                        <UIATextField name="" label="" value="Birthday" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/1/0/3/1/0" x="51.5625" y="300.6875" width="281.25" height="28.125">
                        </UIATextField>
                    </UIATextField>
                </UIATableCell> `

Will appium always return the values from the parent or is this a bug? I tried using
`find_element(xpath: '//UIATextField[@value="Birthday" and @visible="true"]')`
but I get "Selenium::WebDriver::Error::NoSuchElementError: "

appium_lib: 7.0.0
appium_console: 1.0.4
ruby: 2.2.0

**Comment by sofaking** [comment] 2015-08-21 09:35
1) I'd rather post this in appium main repository. I'm 99% sure the issue is not specific to Ruby lib.
2) Couple of ways to investigate it further:
 - Look at 'native' element tree: 
```ruby
 execute_script 'UIATarget.localTarget().frontMostApp().mainWindow().logElementTree()'
```
The output will be shown in appium's console
 - Check if find_element actually can find both TextFields
```ruby
find_elements(xpath: '//UIATextField[@value="Birthday"]').map { |el| el.attribute 'visible' }
```
3) Bonus track. I faced with a couple of weird issues when developers configured accessibility for elements 'manually', meaning through code, not from interface builder. Make sure this is not your case. If yes, then they should explicitly add required element to accessibility layer.

**Comment by JaniJegoroff** [comment] 2015-08-21 15:23
@sofaking Thanks for your comments. I agree this question is better post to main Appium repo.

@uscengineer I'm closing this issue now. Feel free to reopen if this is `ruby_lib` related issue after all.

**Closed by JaniJegoroff** 2015-08-21 15:23 UTC
