### ISSUE TITLE
button/buttons, find/finds methods returning JS error in iOS

### ISSUE THREAD

**Issue by kenkrzeminski** [appium/ruby_lib#332] opened 2015-04-30 15:20 UTC
appium_lib 6.0.0
appium 1.3.7
xcode 6.3.1
iOS 8.3 iPhone 5S simulator

Whenever I call button or buttons, as well as find or finds, it returns a javascript error as follows:

```
[6] pry(main)> button("Photos").click
Selenium::WebDriver::Error::JavascriptError: undefined is not a function (evaluating 'elementProperty.toLowerCase()')
from /Users/username/.rvm/gems/ruby-2.1.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/response.rb:52:in `assert_ok'
```

I tried updating to selenium-webdriver 2.45 as well and still get the same error.

**Comment by kenkrzeminski** [comment] 2015-04-30 15:37
Appium log:

```
info: --> POST /wd/hub/session/422c1b09-58c5-4581-88d3-4868fef5cd83/execute {"script":"        (function() {\n        var opts = {\"typeArray\":[\"UIAButton\"],\"onlyVisible\":true,\"name\":{\"target\":\"Photos\",\"substring\":true,\"insensitive\":true},\"label\":{\"target\":\"Photos\",\"substring\":true,\"insensitive\":true},\"value\":{\"target\":\"Photos\",\"substring\":true,\"insensitive\":true},\"onlyFirst\":true}\n\n        return $.mainWindow()._elementOrElementsByType(opts);\n        })();\n","args":[]}


info: [debug] Pushing command to appium work queue: "        (function() {\n        var opts = {\"typeArray\":[\"UIAButton\"],\"onlyVisible\":true,\"name\":{\"target\":\"Photos\",\"substring\":true,\"insensitive\":true},\"label\":{\"target\":\"Photos\",\"substring\":true,\"insensitive\":true},\"value\":{\"target\":\"Photos\",\"substring\":true,\"insensitive\":true},\"onlyFirst\":true}\n\n        return $.mainWindow()._elementOrElementsByType(opts);\n        })();\n"
info: [debug] Sending command to instruments:         (function() {
        var opts = {"typeArray":["UIAButton"],"onlyVisible":true,"name":{"target":"Photos","substring":true,"insensitive":true},"label":{"target":"Photos","substring":true,"insensitive":true},"value":{"target":"Photos","substring":true,"insensitive":true},"onlyFirst":true}

        return $.mainWindow()._elementOrElementsByType(opts);
        })();



info: [debug] [INST] 2015-04-30 15:34:19 +0000 Debug: Got new command 5 from instruments:         (function() {
               var opts = {"typeArray":["UIAButton"],"onlyVisible":true,"name":{"target":"Photos","substring":true,"insensitive":true},"label":{"target":"Photos","substring":true,"insensitive":true},"value":{"target":"Photos","substring":true,"insensitive":true},"onlyFirst":true}
        return $.mainWindow()._elementOrElementsByType(opts);
        })();




info: [debug] [INST] 2015-04-30 15:34:19 +0000 Debug: evaluating         (function() {
               var opts = {"typeArray":["UIAButton"],"onlyVisible":true,"name":{"target":"Photos","substring":true,"insensitive":true},"label":{"target":"Photos","substring":true,"insensitive":true},"value":{"target":"Photos","substring":true,"insensitive":true},"onlyFirst":true}
        return $.mainWindow()._elementOrElementsByType(opts);
        })();




info: [debug] Socket data received (98 bytes)


info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":17,"value":"undefined is not a function (evaluating 'elementProperty.toLowerCase()')"}
info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"undefined is not a function (evaluating 'elementProperty.toLowerCase()')"},"sessionId":"422c1b09-58c5-4581-88d3-4868fef5cd83"}
info: <-- POST /wd/hub/session/422c1b09-58c5-4581-88d3-4868fef5cd83/execute 500 863.676 ms - 233 


info: [debug] [INST] 2015-04-30 15:34:19 +0000 Error: TypeError: undefined is not a function (evaluating 'elementProperty.toLowerCase()')


info: [IOS_SYSLOG_ROW ] Apr 30 11:34:20 username-mbp.local mstreamd[52932]: (Note ) PS: Media stream daemon stopping.


info: [IOS_SYSLOG_ROW ] Apr 30 11:34:20 username-mbp.local mstreamd[52932]: (Note ) AS: <MSIOSAlbumSharingDaemon: 0x7fc41bd00920>: Shared Streams daemon has shut down.
info: [IOS_SYSLOG_ROW ] Apr 30 11:34:20 username-mbp.local mstreamd[52932]: (Warn ) mstreamd: mstreamd shutting down.


info: [debug] [INST] 2015-04-30 15:34:19 +0000 Error: Error during eval: attributeMatch@file:///Users/username/appium/604CF2F4-66CC-4F38-964B-9ED0457DA257/bootstrap-8211fc30c5af9025.js:2230:54
       getTree@file:///Users/username/appium/604CF2F4-66CC-4F38-964B-9ED0457DA257/bootstrap-8211fc30c5af9025.js:2255:58
getTree@file:///Users/username/appium/604CF2F4-66CC-4F38-964B-9ED0457DA257/bootstrap-8211fc30c5af9025.js:2275:39
getTree@file:///Users/username/appium/604CF2F4-66CC-4F38-964B-9ED0457DA257/bootstrap-8211fc30c5af9025.js:2275:39
_elementOrElementsByType@file:///Users/username/appium/604CF2F4-66CC-4F38-964B-9ED0457DA257/bootstrap-8211fc30c5af9025.js:2282:32
eval code
eval@[native code]
startProcessing@file:///Users/username/appium/604CF2F4-66CC-4F38-964B-9ED0457DA257/bootstrap-8211fc30c5af9025.js:2693:30
bootstrap@file:///Users/username/appium/604CF2F4-66CC-4F38-964B-9ED0457DA257/bootstrap-8211fc30c5af9025.js:2761:31
global code@file:///Users/username/appium/604CF2F4-66CC-4F38-964B-9ED0457DA257/bootstrap-8211fc30c5af9025.js:2770:10



info: [debug] [INST] 2015-04-30 15:34:19 +0000 Debug: responding with:


info: [debug] [INST] 2015-04-30 15:34:19 +0000 Debug: Running system command #6: /Applications/Appium.app/Contents/Resources/node/bin/node /Users/username/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":17,"value":"undefined is not a function (evaluating 'elementProperty.toLowerCase()')"}...
```

**Comment by bootstraponline** [comment] 2015-05-01 01:09
Does this happen on the master branch of ruby_lib?

```ruby
gem 'appium_lib', git: 'https://github.com/appium/ruby_lib.git'
```

**Comment by kenkrzeminski** [comment] 2015-05-01 14:32
Different error on master branch:

```
[6] pry(main)> button("test")
Selenium::Client::CommandError: mainWindow is nil
from /Users/kkrzeminski/.rvm/gems/ruby-2.1.1/gems/appium_lib-6.0.0/lib/appium_lib/ios/helper.rb:555:in `_by_json'
[7] pry(main)> buttons("tesT")
Selenium::Client::CommandError: mainWindow is nil
from /Users/kkrzeminski/.rvm/gems/ruby-2.1.1/gems/appium_lib-6.0.0/lib/appium_lib/ios/helper.rb:555:in `_by_json'
[8] pry(main)> find("test")
Selenium::Client::CommandError: mainWindow is nil
from /Users/kkrzeminski/.rvm/gems/ruby-2.1.1/gems/appium_lib-6.0.0/lib/appium_lib/ios/helper.rb:555:in `_by_json'
[9] pry(main)> finds("test")
Selenium::Client::CommandError: mainWindow is nil
from /Users/kkrzeminski/.rvm/gems/ruby-2.1.1/gems/appium_lib-6.0.0/lib/appium_lib/ios/helper.rb:555:in `_by_json'
[10] pry(main)> text("test")
Selenium::WebDriver::Error::NoSuchElementError: An element could not be located on the page using the given search parameters.
from /Users/kkrzeminski/.rvm/gems/ruby-2.1.1/gems/appium_lib-6.0.0/lib/appium_lib/common/helper.rb:218:in `_no_such_element'
[11] pry(main)> text("Photos")
Selenium::WebDriver::Error::NoSuchElementError: An element could not be located on the page using the given search parameters.
from /Users/kkrzeminski/.rvm/gems/ruby-2.1.1/gems/appium_lib-6.0.0/lib/appium_lib/common/helper.rb:218:in `_no_such_element'
[12] pry(main)> find_element(:name, "Photos")
#<Selenium::WebDriver::Element:0x..f8e8748350f66b7b8 id="0">
[13] pry(main)> 
```

**Comment by kenkrzeminski** [comment] 2015-05-01 14:38
A different error on appium master branch:

```
[6] pry(main)> button("test")
Selenium::Client::CommandError: mainWindow is nil
from /Users/kkrzeminski/.rvm/gems/ruby-2.1.1/gems/appium_lib-6.0.0/lib/appium_lib/ios/helper.rb:555:in `_by_json'
[7] pry(main)> buttons("tesT")
Selenium::Client::CommandError: mainWindow is nil
from /Users/kkrzeminski/.rvm/gems/ruby-2.1.1/gems/appium_lib-6.0.0/lib/appium_lib/ios/helper.rb:555:in `_by_json'
[8] pry(main)> find("test")
Selenium::Client::CommandError: mainWindow is nil
from /Users/kkrzeminski/.rvm/gems/ruby-2.1.1/gems/appium_lib-6.0.0/lib/appium_lib/ios/helper.rb:555:in `_by_json'
[9] pry(main)> finds("test")
Selenium::Client::CommandError: mainWindow is nil
from /Users/kkrzeminski/.rvm/gems/ruby-2.1.1/gems/appium_lib-6.0.0/lib/appium_lib/ios/helper.rb:555:in `_by_json'
[10] pry(main)> text("test")
Selenium::WebDriver::Error::NoSuchElementError: An element could not be located on the page using the given search parameters.
from /Users/kkrzeminski/.rvm/gems/ruby-2.1.1/gems/appium_lib-6.0.0/lib/appium_lib/common/helper.rb:218:in `_no_such_element'
[11] pry(main)> text("Photos")
Selenium::WebDriver::Error::NoSuchElementError: An element could not be located on the page using the given search parameters.
from /Users/kkrzeminski/.rvm/gems/ruby-2.1.1/gems/appium_lib-6.0.0/lib/appium_lib/common/helper.rb:218:in `_no_such_element'
[12] pry(main)> find_element(:name, "Photos")
#<Selenium::WebDriver::Element:0x..f8e8748350f66b7b8 id="0">
```

**Comment by bootstraponline** [comment] 2015-05-01 23:36
Unfortunately the mainWindow being nil randomly is a recent bug in instruments. I recommend using the standard find_element methods provided by selenium as a work around until Apple resolves the issue.

For more details see: https://github.com/appium/appium/issues/4456

Once appium on iOS stops crashing on startup, I will investigate the rspec tests for these helper methods to make sure they pass.
https://github.com/appium/appium/issues/5018

**Comment by mahshadul** [comment] 2015-05-15 15:49
I am using xcode 6.1.1, Appium 1.3.4, appium_lib (7.0.0, 6.0.0), iOS 8.1
also getting this error 
Selenium::Client::CommandError: mainWindow is nil
for 'find'

**Comment by juhlila** [comment] 2016-07-25 19:07
it is still not working

**Comment by bootstraponline** [comment] 2016-07-25 19:10
> it is still not working

the gem is not maintained anymore :( 

https://github.com/appium/ruby_lib/issues/337

**Comment by slipy12** [comment] 2016-12-20 10:43
@juhlila @mahshadul @kenkrzeminski is this still happening? (it works for me)

**Comment by KazuCocoa** [comment] 2017-01-09 06:35
> Unfortunately the mainWindow being nil randomly is a recent bug in instruments. I recommend using the standard find_element methods provided by selenium as a work around until Apple resolves the issue.

This error may be caused by instruments.
In addition, I've changed some logic to using `find_elements` in `button/s` and `text/s`. So, this error don't occur for XCUITest(WDA based driver).

So, I close this issue.

**Closed by KazuCocoa** 2017-01-09 06:35 UTC
