### ISSUE TITLE
Bug: NoMethodError: undefined method `write_session_id' for #<Appium::Core::Driver:0x00007fa69119ce88>

### ISSUE THREAD

**Issue by luizlohn** [appium/ruby_lib#686] opened 2017-10-05 19:52 UTC
## This is a
* [x] Bug report
* [ ] Question
* [ ] Freature Request

## Environment
* Appium version (or git revision): 1.7.1
* `ruby_lib` version: 2.4.2
* Mobile platform/version/device under test: android and ios

## Actual behaviour and steps to reproduce
When I start my tests in the new version of appium_lib this error broke my test:
NoMethodError: undefined method `write_session_id' for #<Appium::Core::Driver:0x00007fa69119ce88>

## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment] 2017-10-06 08:07
Thanks!

https://github.com/appium/ruby_lib/search?utf8=✓&q=write_session_id&type=
the method defined in` lib/appium_lib/driver.rb` but called in `lib/appium_lib/core/driver.rb`. I'll move the method from core to not core I can. If no, I'll move the definition to core.

**Comment by luizlohn** [comment] 2017-10-06 13:12
Thank you @KazuCocoa if you want some help, I can help you!
:)

**Comment by luizlohn** [comment] 2017-10-06 13:34
@KazuCocoa you will release ruby_lib with this correction today?

**Comment by KazuCocoa** [comment] 2017-10-06 14:26
I've confirmed the reproducibility and fixed in https://github.com/appium/ruby_lib/pull/689 
branch: https://github.com/KazuCocoa/ruby_lib/tree/fix_export_session

I'd love to release if current PRs are all green and be able to merge, but I can't promise it because CI queue is stacking.
If you'd like to use the fix version, you can use from https://github.com/KazuCocoa/ruby_lib/tree/fix_export_session so far.
@luizlohn

**Comment by luizlohn** [comment] 2017-10-06 14:28
Perfect @KazuCocoa i will use! THank you

**Closed** 2017-10-06 16:01 UTC

**Comment by KazuCocoa** [comment] 2017-10-07 06:15
published https://rubygems.org/gems/appium_lib/versions/9.7.2
