### ISSUE TITLE
iOS 9 Support

### ISSUE THREAD

**Issue by vkyt** [appium/ruby_lib#352] opened 2015-09-29 20:55 UTC
Getting the following error when running in iOS 9:

**error**: Could not find a device to launch. You requested 'iPhone (9.0 Simulator)', but the available devices were: ["iPad 2 (9.0) [B328C5CE-2B84-4A25-9746-5CCABE1A954C]","iPad Air (9.0) [500A7567-A7FE-4FC3-9B29-454A52545726]","iPad Air 2 (9.0) [509D57D7-E3E4-494E-B20D-B93365DD17F2]","iPad Retina (9.0) [1C5E5C0F-3297-440F-BC9B-0E00E33FBA71]","iPhone 4s (9.0) [6A38CD52-318B-48EB-9CCD-01A1522E0549]","iPhone 5 (9.0) [8A15053C-91B0-4DA1-BDF3-D6305BC226AD]","iPhone 5s (9.0) [5D2765D8-4191-4652-8B7C-688756D9422F]","iPhone 6 (9.0) [3EE5D705-CC38-4472-A435-0B94E3A2AEB6]","iPhone 6 (9.0) + Apple Watch - 38mm (2.0) [EC2A0A08-3BDF-472B-A74F-FD953A82902F]","iPhone 6 Plus (9.0) [F77EDB28-04C3-4567-BD57-5D37431B00C7]","iPhone 6 Plus (9.0) + Apple Watch - 42mm (2.0) [310B50D6-0708-4558-82F8-75D6C57A9E2B]","iPhone 6s (9.0) [9218B513-F447-407A-B999-812ED506813E]","iPhone 6s Plus (9.0) [9D661B52-C764-40D0-B1CD-8887C9E863A1]"]

And then Appium fails to start because it couldn't find a device to lanch.  

Is this related to the iOS support update that's currently on-going for the other languages that Appium supports?

Thanks!

**Comment by KazuCocoa** [comment] 2015-09-30 00:32
The issue is same as https://github.com/appium/appium/issues/5624 .
And which version of Appium did you use ? Latest 1.4.12 resolved some of issues regarding to launching iOS9 simulators. https://github.com/appium/appium/releases/tag/v1.4.12

**Comment by imurchie** [comment] 2015-10-05 13:56
Closing, as not a ruby client issue (see Appium issue linked above).

**Closed by imurchie** 2015-10-05 13:56 UTC
