### ISSUE TITLE
Not able to switch on webview.

### ISSUE THREAD

**Issue by iabhay** [appium/ruby_lib#345] opened 2015-07-09 13:14 UTC
HI, I have a problem that i am not able to switch on webview.When i call getcontexthandles it gives only native_app not WebView even there is a WebView.
I am stuck here please help me out

**Comment by JaniJegoroff** [comment] 2015-07-11 16:00
You need to provide more details otherwise nobody is able to help you out.

- Android or iOS
- Platform version
- Real device or emulator/simulator
- Appium logs
- Code snippet or even better, example project where issue is reproducible

**Comment by iabhay** [comment] 2015-07-12 06:48
HI,
   Fallowing are requested information.

   - Android or iOS: Android 4.4.2
   - Platform version: Windows
   - Real device or emulator/simulator: Real device

Scenario:
1.User open the App.
2.Click on Bus on product listing.
3.Enter required information.
4..Click on search bus.
5.Result page is display that is webview.

On this page i am getting only Native View not web view.

I have attached the code.You can run the code just right click
on sanitytest_testng.xml and run as test ng.
App is under APK folder.

code location :
https://drive.google.com/file/d/0B0QUsT7aTHwCcm5TQVdUTWhNNkE/view?usp=sharing







*Abhay Rai*
Sr Automation Test Engr
Aspire System India Pvt Ltd.
Sec-14 Gurgoan
Mob : +91 9958544199
Email – *abhay.rai@aspiresys.com <http://www.aspiresys.com>*
Website - *www..aspiresys.com <http://www.dbydx.com/>*
Skype : iabhay

**Comment by JaniJegoroff** [comment] 2015-07-12 16:02
This library is for code written in Ruby. Since you are using Java and Appium java-client you should report issues there: https://github.com/appium/java-client

**Comment by JaniJegoroff** [comment] 2015-07-13 09:25
Closing since not relevant issue for this project.

**Closed by JaniJegoroff** 2015-07-13 09:25 UTC
